name: Build

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go get -u ./...
        go build -v ./... ./build/linux/timetable_bot

    - name: Test
      run: go test -v ./...
