name: Build

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go get -u gorm.io/gorm
        go get -u gorm.io/driver/mysql
        go get -u github.com/go-gormigrate/gormigrate/v2
        go get -u github.com/go-telegram-bot-api/telegram-bot-api;
        go get -u github.com/google/uuid
        GO111MODULE=auto GOOS=linux GOARCH=amd64 go build -o build/linux/timetable_bot
