name: Go

on:
  workflow_dispatch:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: go version
    - name: Build
      run: |
        go get -u ./...
        GO111MODULE=auto GOOS=linux GOARCH=amd64 go build -o ./build/linux64/timetable_bot
